package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	"github.com/Pawan2061/timeline_grpc_go/server/graph/generated"
	"github.com/Pawan2061/timeline_grpc_go/server/graph/model"
)

// GetTimeline is the resolver for the getTimeline field.
func (r *queryResolver) GetTimeline(ctx context.Context, userID string) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: GetTimeline - getTimeline"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
