// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: timeline.proto

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineRequest) Reset() {
	*x = TimelineRequest{}
	mi := &file_timeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineRequest) ProtoMessage() {}

func (x *TimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineRequest.ProtoReflect.Descriptor instead.
func (*TimelineRequest) Descriptor() ([]byte, []int) {
	return file_timeline_proto_rawDescGZIP(), []int{0}
}

type TimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineResponse) Reset() {
	*x = TimelineResponse{}
	mi := &file_timeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResponse) ProtoMessage() {}

func (x *TimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResponse.ProtoReflect.Descriptor instead.
func (*TimelineResponse) Descriptor() ([]byte, []int) {
	return file_timeline_proto_rawDescGZIP(), []int{1}
}

func (x *TimelineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_timeline_proto protoreflect.FileDescriptor

const file_timeline_proto_rawDesc = "" +
	"\n" +
	"\x0etimeline.proto\x12\btimeline\"\x11\n" +
	"\x0fTimelineRequest\",\n" +
	"\x10TimelineResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2V\n" +
	"\x0fTimelineService\x12C\n" +
	"\bSayHello\x12\x19.timeline.TimelineRequest\x1a\x1a.timeline.TimelineResponse\"\x00B+Z)github.com/pascalallen/grpc-go/helloworldb\x06proto3"

var (
	file_timeline_proto_rawDescOnce sync.Once
	file_timeline_proto_rawDescData []byte
)

func file_timeline_proto_rawDescGZIP() []byte {
	file_timeline_proto_rawDescOnce.Do(func() {
		file_timeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_timeline_proto_rawDesc), len(file_timeline_proto_rawDesc)))
	})
	return file_timeline_proto_rawDescData
}

var file_timeline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_timeline_proto_goTypes = []any{
	(*TimelineRequest)(nil),  // 0: timeline.TimelineRequest
	(*TimelineResponse)(nil), // 1: timeline.TimelineResponse
}
var file_timeline_proto_depIdxs = []int32{
	0, // 0: timeline.TimelineService.SayHello:input_type -> timeline.TimelineRequest
	1, // 1: timeline.TimelineService.SayHello:output_type -> timeline.TimelineResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_timeline_proto_init() }
func file_timeline_proto_init() {
	if File_timeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_timeline_proto_rawDesc), len(file_timeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timeline_proto_goTypes,
		DependencyIndexes: file_timeline_proto_depIdxs,
		MessageInfos:      file_timeline_proto_msgTypes,
	}.Build()
	File_timeline_proto = out.File
	file_timeline_proto_goTypes = nil
	file_timeline_proto_depIdxs = nil
}
